/// HTML dashboard template for vizier_dashboard(path).
/// The marker VIZIER_JSON_DATA gets replaced with a JSON object at runtime.
/// This template is compiled into the extension binary — no external files needed.
pub const template_before: [*:0]const u8 =
    \\<!DOCTYPE html>
    \\<html lang="en">
    \\<head>
    \\<meta charset="utf-8">
    \\<meta name="viewport" content="width=device-width, initial-scale=1">
    \\<title>Vizier Dashboard</title>
    \\<style>
    \\*{box-sizing:border-box;margin:0;padding:0}
    \\body{font-family:system-ui,-apple-system,sans-serif;background:#f8f9fa;color:#1a1a2e;line-height:1.6}
    \\header{background:#1a1a2e;color:#fff;padding:1.2em 2em;display:flex;align-items:center;gap:1em}
    \\header h1{font-size:1.4em;font-weight:600}
    \\header .stats{margin-left:auto;font-size:0.85em;opacity:0.8}
    \\nav{background:#2d2d44;padding:0 2em;display:flex;gap:0}
    \\nav button{background:none;border:none;color:#aaa;padding:0.8em 1.5em;cursor:pointer;font-size:0.9em;border-bottom:3px solid transparent;transition:all 0.2s}
    \\nav button:hover{color:#fff}
    \\nav button.active{color:#fff;border-bottom-color:#6c63ff}
    \\.container{max-width:1200px;margin:0 auto;padding:1.5em}
    \\.tab{display:none}
    \\.tab.active{display:block}
    \\.card{background:#fff;border-radius:8px;box-shadow:0 1px 3px rgba(0,0,0,0.1);margin-bottom:1.2em;overflow:hidden}
    \\.card-header{padding:1em 1.5em;border-bottom:1px solid #eee;font-weight:600;display:flex;align-items:center;gap:0.5em}
    \\.card-body{padding:1.2em 1.5em}
    \\table{width:100%;border-collapse:collapse;font-size:0.88em}
    \\th{text-align:left;padding:0.6em 0.8em;background:#f5f5f7;color:#555;font-weight:600;border-bottom:2px solid #e5e7eb;cursor:pointer;user-select:none}
    \\th:hover{background:#eee}
    \\td{padding:0.6em 0.8em;border-bottom:1px solid #f0f0f0}
    \\tr:hover td{background:#f8f8ff}
    \\.kind{display:inline-block;padding:0.15em 0.6em;border-radius:4px;font-size:0.82em;font-weight:500}
    \\.kind-create_index{background:#dbeafe;color:#1d4ed8}
    \\.kind-rewrite_sorted_table{background:#fef3c7;color:#92400e}
    \\.kind-drop_redundant_index{background:#fce7f3;color:#9d174d}
    \\.kind-parquet_sort_order{background:#d1fae5;color:#065f46}
    \\.kind-parquet_partition{background:#e0e7ff;color:#3730a3}
    \\.kind-parquet_row_group_size{background:#e0e7ff;color:#3730a3}
    \\.kind-create_summary_table{background:#ede9fe;color:#5b21b6}
    \\.kind-sort_for_join{background:#fef3c7;color:#92400e}
    \\.kind-no_action{background:#f3f4f6;color:#6b7280}
    \\.score-bar{display:inline-block;height:8px;border-radius:4px;background:#e5e7eb;width:60px;position:relative}
    \\.score-fill{height:100%;border-radius:4px;background:#6c63ff}
    \\.verdict-regression{color:#dc2626;font-weight:600}
    \\.verdict-improved{color:#16a34a;font-weight:600}
    \\.verdict-stable{color:#6b7280}
    \\.sql-text{font-family:monospace;font-size:0.82em;color:#374151;max-width:400px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
    \\.copy-btn{background:#f3f4f6;border:1px solid #d1d5db;border-radius:4px;padding:0.2em 0.5em;cursor:pointer;font-size:0.78em}
    \\.copy-btn:hover{background:#e5e7eb}
    \\.empty{text-align:center;padding:2em;color:#9ca3af}
    \\footer{text-align:center;padding:2em;color:#9ca3af;font-size:0.8em}
    \\</style>
    \\</head>
    \\<body>
    \\<header>
    \\  <h1>Vizier Dashboard</h1>
    \\  <div class="stats" id="header-stats"></div>
    \\</header>
    \\<nav>
    \\  <button class="active" onclick="showTab('recs',this)">Recommendations</button>
    \\  <button onclick="showTab('workload',this)">Workload</button>
    \\  <button onclick="showTab('actions',this)">Applied Changes</button>
    \\  <button onclick="showTab('replay',this)">Replay</button>
    \\  <button onclick="showTab('overview',this)">Overview</button>
    \\</nav>
    \\<div class="container">
    \\  <div id="recs" class="tab active"></div>
    \\  <div id="workload" class="tab"></div>
    \\  <div id="actions" class="tab"></div>
    \\  <div id="replay" class="tab"></div>
    \\  <div id="overview" class="tab"></div>
    \\</div>
    \\<footer>Generated by Vizier</footer>
    \\<script>
    \\const D=
;

pub const template_after: [*:0]const u8 =
    \\;
    \\function showTab(id,btn){document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('nav button').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active')}
    \\function scoreBar(v){const w=Math.round(Math.min(v,1)*100);return`<span class="score-bar"><span class="score-fill" style="width:${w}%"></span></span> ${v.toFixed(2)}`}
    \\function kindBadge(k){return`<span class="kind kind-${k}">${k}</span>`}
    \\function copyBtn(sql){return`<button class="copy-btn" onclick="navigator.clipboard.writeText(this.dataset.sql)" data-sql="${sql.replace(/"/g,'&quot;')}">copy</button>`}
    \\function sortTable(tbody,col,rows){let asc=tbody.dataset.sortCol==col?tbody.dataset.sortAsc!=='true':true;tbody.dataset.sortCol=col;tbody.dataset.sortAsc=asc;rows.sort((a,b)=>{let va=a[col],vb=b[col];if(typeof va==='number')return asc?va-vb:vb-va;return asc?String(va).localeCompare(String(vb)):String(vb).localeCompare(String(va))});renderRows(tbody,rows,tbody.dataset.renderer)}
    \\function renderRows(tbody,rows,renderer){tbody.innerHTML=rows.map(window[renderer]).join('')}
    \\function recRow(r){return`<tr><td>${r.id}</td><td>${kindBadge(r.kind)}</td><td>${r.table_name}</td><td>${scoreBar(r.score)}</td><td>${r.confidence.toFixed(2)}</td><td>${r.reason}</td><td>${copyBtn(r.sql)}</td></tr>`}
    \\function wlRow(r){return`<tr><td>${r.sig}</td><td class="sql-text" title="${r.sql.replace(/"/g,'&quot;')}">${r.sql}</td><td>${r.runs}</td><td>${r.avg_ms.toFixed(2)}</td></tr>`}
    \\function actRow(r){return`<tr><td>${r.id}</td><td class="sql-text">${r.sql}</td><td>${r.success?'yes':'no'}</td><td>${r.notes}</td><td>${r.can_rollback?'yes':'no'}</td></tr>`}
    \\function repRow(r){return`<tr><td>${r.sig}</td><td class="sql-text">${r.sql}</td><td>${r.avg_ms.toFixed(2)}</td><td class="verdict-${r.verdict}">${r.verdict}</td></tr>`}
    \\function init(){
    \\  const recs=D.recommendations||[];const wl=D.workload||[];const acts=D.actions||[];const rep=D.replay||[];
    \\  document.getElementById('header-stats').textContent=`${recs.length} recommendations | ${wl.length} queries | ${acts.length} applied`;
    \\  const recsEl=document.getElementById('recs');
    \\  if(recs.length){recsEl.innerHTML=`<div class="card"><div class="card-header">Pending Recommendations (${recs.length})</div><div class="card-body"><table><thead><tr><th onclick="sortTable(tbody,'id',recs)">ID</th><th onclick="sortTable(tbody,'kind',recs)">Kind</th><th onclick="sortTable(tbody,'table_name',recs)">Table</th><th onclick="sortTable(tbody,'score',recs)">Score</th><th onclick="sortTable(tbody,'confidence',recs)">Conf</th><th>Reason</th><th>SQL</th></tr></thead><tbody id="recs-body" data-renderer="recRow"></tbody></table></div></div>`;const tbody=document.getElementById('recs-body');renderRows(tbody,recs,'recRow')}else{recsEl.innerHTML='<div class="card"><div class="card-body empty">No pending recommendations</div></div>'}
    \\  const wlEl=document.getElementById('workload');
    \\  if(wl.length){wlEl.innerHTML=`<div class="card"><div class="card-header">Captured Workload (${wl.length} queries)</div><div class="card-body"><table><thead><tr><th>Signature</th><th>SQL</th><th onclick="sortTable(wlBody,'runs',wl)">Runs</th><th onclick="sortTable(wlBody,'avg_ms',wl)">Avg ms</th></tr></thead><tbody id="wl-body" data-renderer="wlRow"></tbody></table></div></div>`;const wlBody=document.getElementById('wl-body');renderRows(wlBody,wl,'wlRow')}else{wlEl.innerHTML='<div class="card"><div class="card-body empty">No captured queries</div></div>'}
    \\  const actEl=document.getElementById('actions');
    \\  if(acts.length){actEl.innerHTML=`<div class="card"><div class="card-header">Applied Changes (${acts.length})</div><div class="card-body"><table><thead><tr><th>ID</th><th>SQL</th><th>Success</th><th>Notes</th><th>Rollback</th></tr></thead><tbody id="act-body" data-renderer="actRow"></tbody></table></div></div>`;const actBody=document.getElementById('act-body');renderRows(actBody,acts,'actRow')}else{actEl.innerHTML='<div class="card"><div class="card-body empty">No applied changes</div></div>'}
    \\  const repEl=document.getElementById('replay');
    \\  if(rep.length){repEl.innerHTML=`<div class="card"><div class="card-header">Replay Results (${rep.length} queries)</div><div class="card-body"><table><thead><tr><th>Signature</th><th>SQL</th><th onclick="sortTable(repBody,'avg_ms',rep)">Avg ms</th><th>Verdict</th></tr></thead><tbody id="rep-body" data-renderer="repRow"></tbody></table></div></div>`;const repBody=document.getElementById('rep-body');renderRows(repBody,rep,'repRow')}else{repEl.innerHTML='<div class="card"><div class="card-body empty">No replay results — run vizier_replay() first</div></div>'}
    \\  document.getElementById('overview').innerHTML=`<div class="card"><div class="card-header">Summary</div><div class="card-body"><p><strong>${recs.length}</strong> pending recommendations across <strong>${[...new Set(recs.map(r=>r.table_name))].length}</strong> tables</p><p><strong>${wl.length}</strong> captured query patterns, <strong>${wl.reduce((s,w)=>s+w.runs,0)}</strong> total executions</p><p><strong>${acts.length}</strong> changes applied, <strong>${acts.filter(a=>a.can_rollback).length}</strong> reversible</p></div></div>`
    \\}
    \\init();
    \\</script>
    \\</body></html>
;
